// Generated by mdo — regenerated on every `mdo slides` run.
import { defineConfig } from "astro/config";

export default defineConfig({
  output: "static",
  // `mdo slides --watch` serves the markdown's directory as public/ so
  // relative image paths resolve in the dev server. Builds inline images.
  publicDir: process.env.MDO_PUBLIC_DIR || "./public",
  devToolbar: { enabled: false },
  build: {
    // Produce a single self-contained index.html (styles inline).
    inlineStylesheets: "always",
  },
  vite: {
    build: {
      // ...and scripts/assets inline as well.
      assetsInlineLimit: 100_000_000,
    },
    server: {
      // Astro is installed once in a shared runtime dir above this project.
      fs: { allow: %%FS_ALLOW%% },
    },
  },
});
